### ISSUE TITLE
Pathogen install instructions are incorrect

### ISSUE THREAD

**Issue by antun** [Asheq/close-buffers.vim#14]
STEPS
Follow the Pathogen instructions in the README:

`cd ~/.vim/bundle && git clone git://github.com/asheq/close-buffers.git`

RESULT
```
Cloning into 'close-buffers'...
fatal: remote error: 
  Repository not found.

```

I'll fork and submit a PR...

**Comment by antun** [comment]
PR submitted: https://github.com/Asheq/close-buffers.vim/pull/15

**Comment by Asheq** [comment]
Thanks for the PR!
