### ISSUE TITLE
Support nnoremap : ; in Bdelete select

### ISSUE THREAD

**Issue by davidsierradz** [Asheq/close-buffers.vim#9]
I have the following remappings in my init.vim:

```vimscript
nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;
```

In:
https://github.com/Asheq/close-buffers.vim/blob/681961db24974e44ddb034a00d961344843f5de1/plugin/close-buffers.vim#L56 

You are calling `:` but it's interpreting as `;`, so the command doesn't work; checking `:help feedkeys()`, we can pass a second argument to `feedkeys`  with a `'n'` and the keys will not use remaps, this works:

```vimscript
call feedkeys(':' . s:append_bang(a:command, a:bang) . ' ', 'n')
```

But I don't know if this change could have undesired effects, what do you think?

Thanks

**Comment by Asheq** [comment]
Thanks for the report! I don't foresee any problems with your solution. Do you mind submitting a PR?
